import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkOnly } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache CSS, JS, and Web Worker files with a Stale-While-Revalidate strategy.
registerRoute(
    ({ request }) =>
        request.destination === 'style' ||
        request.destination === 'script' ||
        request.destination === 'worker',
    new StaleWhileRevalidate({
        cacheName: 'hff-assets',
    })
);

// Cache images with a Stale-While-Revalidate strategy.
registerRoute(
    ({ request }) => request.destination === 'image',
    new StaleWhileRevalidate({
        cacheName: 'hff-images',
    })
);

// Background Sync for Analytics/Submissions
// This will retry failed POST requests when the user comes back online
const bgSyncPlugin = new BackgroundSyncPlugin('hff-sync-queue', {
    maxRetentionTime: 24 * 60, // Retry for up to 24 Hours
});

registerRoute(
    ({ url }) => url.pathname.startsWith('/api/submissions'),
    new NetworkOnly({
        plugins: [bgSyncPlugin],
    }),
    'POST'
);

registerRoute(
    ({ url }) => url.pathname.startsWith('/api/analytics'),
    new NetworkOnly({
        plugins: [bgSyncPlugin],
    }),
    'POST'
);

// Handle offline navigation by serving index.html
registerRoute(
    ({ request }) => request.mode === 'navigate',
    new StaleWhileRevalidate({
        cacheName: 'hff-navigation',
    })
);

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
