-- Migrations for HFF Dashboard V2
-- Moving from SQLite to Supabase Postgres

-- 1. Create registrations table
CREATE TABLE IF NOT EXISTS registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT gen_random_uuid(),
    first_name TEXT,
    last_name TEXT,
    gender TEXT,
    age TEXT,
    other_1 TEXT,
    education TEXT,
    marital_status TEXT,
    other_2 TEXT,
    occupation TEXT,
    attendance JSONB DEFAULT '[]'::jsonb,
    sync_status TEXT DEFAULT 'pending',
    type TEXT,
    facilitator_uuid UUID,
    source TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create participants table
CREATE TABLE IF NOT EXISTS participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT gen_random_uuid(),
    external_id TEXT,
    first_name TEXT,
    last_name TEXT,
    name TEXT, -- Some client logic uses 'name' directly
    gender TEXT,
    age TEXT,
    other_1 TEXT,
    education TEXT,
    marital_status TEXT,
    other_2 TEXT,
    occupation TEXT,
    attendance JSONB DEFAULT '[]'::jsonb,
    sync_status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create notes table (for testing)
CREATE TABLE IF NOT EXISTS notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;

-- 5. Create basic policies (Allowing all for now as per dashboard requirements, 
-- but ensuring RLS is enabled. In production, these should be restricted to authenticated users.)
CREATE POLICY "Allow public access to registrations" ON registrations FOR ALL USING (true);
CREATE POLICY "Allow public access to participants" ON participants FOR ALL USING (true);
CREATE POLICY "Allow public access to notes" ON notes FOR ALL USING (true);
