-- Migration: Create registration_queue and trigger
CREATE TABLE IF NOT EXISTS public.registration_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id UUID NOT NULL REFERENCES public.registrations(uuid) ON DELETE CASCADE,
    payload JSONB NOT NULL,
    processed BOOLEAN DEFAULT FALSE,
    processed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for performance
CREATE INDEX IF NOT EXISTS idx_registration_queue_processed ON public.registration_queue(processed) WHERE processed = FALSE;

-- Trigger Function to populate the queue
CREATE OR REPLACE FUNCTION public.fn_populate_registration_queue()
RETURNS TRIGGER AS $$
BEGIN
    -- Only queue if it's a participant
    -- Adjust 'type' and 'participant' if your schema uses different names
    IF (NEW.type = 'participant') THEN
        INSERT INTO public.registration_queue (registration_id, payload)
        VALUES (NEW.uuid, to_jsonb(NEW));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create the trigger
DROP TRIGGER IF EXISTS tr_populate_registration_queue ON public.registrations;
CREATE TRIGGER tr_populate_registration_queue
AFTER INSERT ON public.registrations
FOR EACH ROW
EXECUTE FUNCTION public.fn_populate_registration_queue();
